name: Tagger

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
    movetag:
      runs-on: ubuntu-latest
      steps:
      - name: Advanced tagger. Moves major tag to latest minor tag
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}          
          script: |
            var re = /refs\/tags\/(v(\d*(\.\d*)*))/i,
              ref = process.env['GITHUB_REF'],
              match = ref.match(re);
            console.log('Context: ', context);
            console.log('Context.repo: ', context.repo);
            if (match == null)
              return;
              
            var tag_name = match[1],
              tag_ver = match[2],
              base_ver = tag_name.substr(0, tag_name.lastIndexOf('.'));
            console.log(tag_name, tag_ver, base_ver);
            console.log('Base ver', base_ver);
            if (base_ver === '') {
              console.error("Error: Couldn't eval base version");
              return;
            }
            
            let base_ref = "tags/" + base_ver;
            
            try {
              console.log('Deleting base ref: ', base_ref);
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: base_ref
              })
            } catch (e) {
              console.log("The base tag doesn't exist yet: " + e);
              console.log("Creating a new one");
            }
            console.log('Recreating base ref: ', base_ref);
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/" + base_ref,
              sha: context.sha
            }) 
