name: Tagger

on:
  create:
    tags:

jobs:
    movetag:
      runs-on: ubuntu-latest
      steps:
      - name: Advanced tagger. Moves major tag to latest minor tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}          
          script: |
            var re = /refs\/tags\/(v(\d*(\.\d*)*))/i,
              ref = process.env['GITHUB_REF'],
              match = ref.match(re);
            console.log(re);
            console.log(ref);
            console.log(match);
            if (match == null)
              return;
              
            return;

            var tag_name = match[1],
              tag_ver = match[2],
              base_re = /v\d*(\.\d*)*/g,
              base_match = tag_name.matchAll(base_re);
            if (base_match[0].length < 2)
              return;
            let base_ver = tag_ver.substr(0, tag_ver.length - base_match[0][1].length);
            console.log(tag_name, tag_ver, base_re, base_match);
            console.log('Base ver', base_ver);
            return ;
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/nightly"
                })
            } catch (e) {
              console.log("The nightly tag doesn't exist yet: " + e)
            }
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly",
              sha: context.sha
            })*/
