name: Tagger

on:
  create:
    tags:

jobs:
    movetag:
      runs-on: ubuntu-latest
      steps:
      - name: Advanced tagger. Moves major tag to latest minor tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}          
          script: |
            let re = /refs\/tags\/(v(\d*(\.\d*)*))/i,
              ref = process.env['GITHUB_REF'],
              match = ref.match(re);
            console.log(re);
            console.log(ref);
            console.log(match);
            if (match == null)
              return;

            let tag_name = match[1],
              tag_ver = match[2],
              base_re = /(v\d*(\.\d*)*)\.\d*/i,
              base_match = tag_name.match(base_re);
            console.log(tag_name, tag_ver, base_re, base_match);
            return;
              
            //console.log(match, tag_name, tag_ver);
            //console.log("Environment: ",  process.env);
            //console.log(context.repo);
            /*try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/nightly"
                })
            } catch (e) {
              console.log("The nightly tag doesn't exist yet: " + e)
            }
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly",
              sha: context.sha
            })*/
